### ISSUE TITLE
번역 진행 문서 관련 제안

### ISSUE THREAD

**Issue by cprayer** [yeonjuan/Typescript-Handbook-ko#107]
안녕하세요! 열심히 번역해주셔서 감사합니다.

다름이 아니라, 번역 진행 도중인 문서에 관련하여 제안이 있는데요.
현재 READMD는 작성중..이라고 통일되어 있는데, 실제 번역 문서 안에 들어갔을 때는 작성중...이 없는 경우도 있고, 있더라도 글자 / 마크다운 형식이 통일이 되어 있지 않아서요!  

아직 번역이 되지 않은 부분은 원문으로 올리거나 통일된 형식으로 작성중이라는 것을 알 수 있게 적혀 있으면 좋을 듯 하여 이슈 남겨봅니다. (사실 크게 중요한 사항은 아니기에 고려해보시고 판단해주시면 좋을 것 같애요!) 

감사합니다!

**Comment by yeonjuan** [comment]
@cprayer 
제안 감사합니다!

> 아직 번역이 되지 않은 부분은 원문으로 올리거나 통일된 형식으로 작성중이라는 것을 알 수 있게 적혀 있으면 좋을 듯 하여 이슈 남겨봅니다. 

이 부분은 #105 에서 진행되었는데요, 이미 번역을 하기로 이슈에 등록한 챕터는 충돌을 피하기 위해 원문을 올리지 않았습니다!
그래도 번역 진행 상황을 잘 알 수 있는 방법이 필요하긴 하겠네요 .. ㅎ 좋은 방법 있으면 제안 주시면 감사하겠습니다.

>  실제 번역 문서 안에 들어갔을 때는 없는 경우도 있고, 있더라도 마크다운 형식이 통일이 되어 있지 않아서요!

기본적으로는, [원문 TypeScript handbook](https://github.com/microsoft/TypeScript-Handbook/tree/master/pages) 과 형식을 일치시키려고 하고 있습니다. 이 부분은 한번 확인해 보겠습니다!  감사합니다 :)

**Comment by bumkeyy** [comment]
@cprayer 
좋은 제안 감사합니다! 😄 

진행 상황을 모두가 한눈에 볼 수 있도록 공유해야 한다는 점에 동의합니다!
또한 프로젝트 진행에 있어 룰이 좀 더 있어야 할 것 같네요..

빠른 시일내로 정리해서 좀 더 탄탄한 프로젝트로 만들어 보겠습니당 :)

**Comment by yeonjuan** [comment]
@cprayer @Bumkeyy 
[진행상황](https://github.com/yeonjuan/Typescript-Handbook-ko/projects/1) 을 README.d 랑 CONTRIBUTING.md 에 링크로 추가하도록 하겠습니다.

**Comment by bumkeyy** [comment]
해당 이슈는 반영했으므로 클로즈하겠습니다.
