### ISSUE TITLE
Type Checking JavaScript Files 번역

### ISSUE THREAD

**Issue by yeonjuan** [yeonjuan/Typescript-Handbook-ko#110]
* [원문](https://github.com/yeonjuan/Typescript-Handbook-ko/blob/master/type-checking-javascript-files.md)

**Comment by Myoji** [comment]
해당 섹션 번역 담당하겠습니다

별도로 이슈 등록하면 될까요?

---

원본링크 :  [Type Checking JavaScript Files](http://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html)
범위 : 전체
Due Date : 2020/03/01

**Comment by bumkeyy** [comment]
@Myoji 
별도의 이슈는 생성 안해도 됩니다!
감사합니다 👍 👍

**Comment by bumkeyy** [comment]
@Myoji 
번역 기한은 정해주세요 :)

**Comment by yeonjuan** [comment]
#110 closed  by #127
