### ISSUE TITLE
Tutorials/TypeScript in 5 minutes 번역 필요

### ISSUE THREAD

**Issue by bumkeyy** [yeonjuan/Typescript-Handbook-ko#138]
* [원문](https://github.com/yeonjuan/Typescript-Handbook-ko/blob/master/tutorials/TypeScript%20in%205%20minutes.md)

**Comment by dvlprsh** [comment]
Tutorials/TypeScript in 5 minutes 할당 부탁드립니다~

원본링크 : [Tutorials/TypeScript in 5 minutes](https://github.com/yeonjuan/Typescript-Handbook-ko/blob/master/tutorials/TypeScript%20in%205%20minutes.md)
범위 : 전체
Due Date : 2020/03/17

**Comment by yeonjuan** [comment]
@dvlprsh  영문 파일 그대로 덮어써서 번역하시면 됩니다!! 계속 참여해주셔서 감사합니다!  👍
