### ISSUE TITLE
Declaration Files/Do's and Don'ts 번역 필요

### ISSUE THREAD

**Issue by bumkeyy** [yeonjuan/Typescript-Handbook-ko#146]
* [원문](https://github.com/yeonjuan/Typescript-Handbook-ko/blob/master/declaration%20files/Do's%20and%20Don'ts.md)

**Comment by yeonjuan** [comment]
제가 담당하겠습니다
~기한: 3월 25일~
~기한: 4월 1일~
기한: 4월 10일
