### ISSUE TITLE
type assertion 번역 관련

### ISSUE THREAD

**Issue by guyeol** [yeonjuan/Typescript-Handbook-ko#17]
보통의 경우 '단언'이라고 번역하는 것 같은데

'타입 단언'이라고 번역하는게 좋을까요? 

[위키백과](https://ko.wikipedia.org/wiki/%ED%91%9C%EB%AA%85)에서는 '표명'이란 표현을 쓰지만 의미상 맞지 않는 것 같구요

원어 그대로 type assertion이라고 하는 것도 괜찮을 것 같습니다

**Comment by bumkeyy** [comment]
번역을 해도 쉽게 와닿지 않는 표현은 원어 그대로 쓰는게 어떨까요? 😄

**Comment by yeonjuan** [comment]
@guyeol @Bumkeyy 
저도 `표명`은 어색한것 같아요.
https://github.com/nodejs/nodejs-ko/issues/51
요기 이슈를 보면, `단언` 도 크게 이상하진 않을 것 같은데 어떻게 생각하시나요. 

> 원어 그대로 type assertion이라고 하는 것도 괜찮을 것 같습니다

전 type assertion 이라고 쓰는 것 보단 `타입 어설션`, `타입 어설션` 보단 `타입 단언`이 더 나을 것 같긴합니다.

**Comment by guyeol** [comment]
`타입 단언`으로 번역하도록 하겠습니다

`단언`으로 번역하는 경우가 많아 의미전달이 충분히 가능할 듯 싶네요!

**Comment by yeonjuan** [comment]
위키에 정리되었으니 이슈를 닫겠습니다.
