### ISSUE TITLE
원문에서 이탤릭체 번역관련

### ISSUE THREAD

**Issue by bumkeyy** [yeonjuan/Typescript-Handbook-ko#19]
원문 Classes Documentation에서 

This example shows the most basic inheritance feature: classes inherit properties and methods from base classes. Here, `Dog` is a *derived* class that derives from the `Animal` *base* class using the `extends` keyword. Derived classes are often called *subclasses*, and base classes are often called *superclasses*.

두번째 줄에 *derived* 는 *파생된* , *base*는 *기초* 라고 번역을 해도 괜찮을 것 같은데, 

맨 아랫줄에 *subclasses*와 *superclasses* 는 용어를 정하는 부분이라서 *하위클래스(subclasses)*, *상위클래스(superclasses)* 처럼 ()를 붙여서 첨부해주는 건 어떨까요?

**Comment by guyeol** [comment]
_파생_ 클래스, _기반_ 클래스 라고 하는건 어떨까요?

그렇게들 많이 사용하고 있는 것 같습니다!

**Comment by yeonjuan** [comment]
@Bumkeyy 
> 맨 아랫줄에 subclasses와 superclasses 는 용어를 정하는 부분이라서 하위클래스(subclasses), 상위클래스(superclasses) 처럼 ()를 붙여서 첨부해주는 건 어떨까요?

단어가 처음 등장할때는 첨부해주고, 이후에는 한글로 쓰는 방법이죠?? 찬성합니다

**Comment by yeonjuan** [comment]
위키에 정리되었으니 이슈를 닫겠습니다.
