### ISSUE TITLE
제목 포맷 통일

### ISSUE THREAD

**Issue by bumkeyy** [yeonjuan/Typescript-Handbook-ko#35]
안녕하세요. 😄 
다들 번역에 힘써주시느라 고생이 많으십니다.^^ 

확인하다 보니 제목들이 파일마다 제각각 인 것 같습니다. 
예를 들어 
# Static Properties 

-> 

# 전역 변수 (Static Properties)

로 번역을 먼저 쓰고 한칸 띄어 쓴 후에 원어를 괄호 안에 넣어주는 걸로 통일하는 방식이 어떤가요?
혹시 의견 있으면 부담없이 알려주세요!

화이팅입니다 💪💪💪

**Comment by yeonjuan** [comment]
동의 합니다!. 단 키워드 예를 들어 const, let 등등 번역하기 어려운 단어(?)는 예외로 하면 좋겠습니다.

**Comment by guyeol** [comment]
좋은 것 같아요 저도 동의합니다~

**Comment by bumkeyy** [comment]
그럼 const, let 과 같은 번역하기 어려운 단어들은 원어로 쓰고, 번역할 수 있는 제목들은 
[번역] (원어) 
로 하는 것으로 통일하겠습니다. 위키에 정리해서 곧 올려 놓을게요!

감사합니다 😄

**Comment by yeonjuan** [comment]
위키에 정리되었으니 이슈를 닫겠습니다.
