### ISSUE TITLE
주석은 번역을 해야할까요?

### ISSUE THREAD

**Issue by guyeol** [yeonjuan/Typescript-Handbook-ko#45]
삽입된 코드 안에 주석이 들어있는 경우가 많은데 주석을 번역해야할까요??

컴파일러가 던지는 에러 내용이 주석에 있는 경우도 있어서 이 경우엔 번역을 하지 않는게 좋을 것 같은데

어떻게 생각하시나요?

예를 들어
```ts
let mySearch: SearchFunc;

// error: Type '(src: string, sub: string) => string' is not assignable to type 'SearchFunc'.
// Type 'string' is not assignable to type 'boolean'.
mySearch = function(src, sub) {
  let result = src.search(sub);
  return "string";
};
```
이런 경우가 있고
```ts
interface NumberDictionary {
    [index: string]: number;
    length: number;    // ok, length is a number
    name: string;      // error, the type of 'name' is not a subtype of the indexer
}
```
이런 경우도 있겠네요

**Comment by yeonjuan** [comment]
@guyeol  에러메시지는 하지 말고, 그 외 설명은 번역하자는 말씀이신 가요? 찬성입니당.

**Comment by bumkeyy** [comment]
@guyeol 에러메시지까지 번역할 필요는 없을 것 같습니다 😄

**Comment by guyeol** [comment]
네네! 에러메시지는 그대로 두고 나머지는 번역하는걸로 하면 좋을듯해요!

**Comment by bumkeyy** [comment]
@guyeol @yeonjuan 
코드 내에 주석에서 ok, error 가 자주 보이는데 일관적으로 번역하는 건 어떨까요?
예를 들어
```
ok -> 성공 or 좋아요
error -> 실패 or 오류
```

더 좋은 의견 있으면 알려주세요 😄

**Comment by yeonjuan** [comment]
@Bumkeyy  Ok: 성공, Error:오류 혹은 에러 어떤가요

**Comment by bumkeyy** [comment]
@yeonjuan 
```
ok:성공
error:오류
```
로 통일하겠습니다. [번역 규칙](https://github.com/yeonjuan/Typescript-Handbook-ko/wiki/%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)에 반영하겠습니다. 😄

**Comment by bumkeyy** [comment]
위키에 정리되었으니 이슈를 닫겠습니다.
