### ISSUE TITLE
Mixins 번역

### ISSUE THREAD

**Issue by bobfull** [yeonjuan/Typescript-Handbook-ko#58]
원본링크: https://www.typescriptlang.org/docs/handbook/mixins.html\
범위: 전체
Due Date: 2020/02/29

**Comment by yeonjuan** [comment]
@bobfull 감사합니다 👍

**Comment by bumkeyy** [comment]
@bobfull  환영합니다 😄

**Comment by bobfull** [comment]
개인사정으로 Due Date : 03/06으로 변경합니다..

**Comment by bumkeyy** [comment]
@bobfull 알겠습니다 😄

**Comment by bumkeyy** [comment]
@bobfull  현재 어디까지 진행이 되었나요?

**Comment by bobfull** [comment]
금일 올리도록 하겠습니다
