### ISSUE TITLE
Namespaces 번역

### ISSUE THREAD

**Issue by ye-geeee** [yeonjuan/Typescript-Handbook-ko#70]
원본링크: [Namespaces](https://www.typescriptlang.org/docs/handbook/namespaces.html)

범위: 전체

Due Date: 2020/02/27

**Comment by yeonjuan** [comment]
@ye-geeee  감사합니다 !! 💯

**Comment by yeonjuan** [comment]
@ye-geeee 
> Due Date: 2020/02/23

진행상황 공유 가능할까요? 혹시 시간이 더 필요하면 날짜를 변경해도 괜찮습니다. 👍

**Comment by ye-geeee** [comment]
@yeonjuan 넵 날짜 변경하였습니다. 금방 올리도록 하겠습니다. 감사합니다!!
